version: "3.9"

services:

  php:
    container_name: form-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=form.local"
    volumes:
      - .:/var/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  nginx:
    container_name: form-nginx
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    container_name: form-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mailpit:
    image: axllent/mailpit
    container_name: form-mailpit
    ports:
     - "8025:8025"
     - "1025:1025"

  node:
    image: node:19
    container_name: form-node
    command: bash -c "npm install && npm run build"
    working_dir: /var/www
    volumes:
      - .:/var/www

volumes:
  mysql_data:
